### ISSUE TITLE
`send()` on Python 2.7 sends data in clear text

### ISSUE THREAD

**Issue by drbild** [wolfSSL/wolfssl-py#1]
On Python 2.7, calling `SSLSocket.send(data)` results in the data being sent in clear text. 

Overriding methods like `socket.send` and `socket.recv` in a subclass is not sufficient.  The super class implementation (plain `socket.send`) is called instead of the subclass implementation (`SSLSocket.send`).  They are treated specially by `socket`, so must be handled specially in subclasses.  

See https://github.com/python/cpython/blob/ad65d09fd02512b2ccf500f6c11063f705c9cd28/Lib/ssl.py#L576 for how the built-in `ssl` module handles this.

**Comment by drbild** [comment]
Hi @kaleb-himes ,

I don't have a script for you, sorry.  This problem manifested inside one of our apps, which isn't easy to separate.

It should be fairly quick to reproduce though.  Just connect to an SSL server and pass some data to `send`.  Observe the stream in Wireshark, and you'll see the plain text transit the wire.

**Comment by cconlon** [comment]
Hi @drbild 

With some recent changes that we merged into master, I think this should now be fixed.  Thanks for the report!

Best Regards,
Chris
