### ISSUE TITLE
wolfssl-py, enable cipher suite

### ISSUE THREAD

**Issue by xoda** [wolfSSL/wolfssl-py#15]
Dear wolfssl-py developers,
I'm using your library to try to connect to an old corporate server, with sslv3 and SSL_RSA_WITH_RC4_128_SHA as a cipher (yeah, I know it's bad).

I'm struggling to enable the cipher suite I need.
```
$ python3 example.py
Traceback (most recent call last):
  File "example.py", line 32, in <module>
    context = wolfssl.wrap_socket(bind_socket, ciphers='SSL_RSA_WITH_RC4_128_SHA')
  File "/usr/local/lib/python3.7/site-packages/wolfssl/__init__.py", line 904, in wrap_socket
    ciphers=ciphers)
  File "/usr/local/lib/python3.7/site-packages/wolfssl/__init__.py", line 388, in __init__
    self._context.set_ciphers(ciphers)
  File "/usr/local/lib/python3.7/site-packages/wolfssl/__init__.py", line 257, in set_ciphers
    raise SSLError("Unable to set cipher list")
wolfssl.exceptions.SSLError: Unable to set cipher list
```

I installed wolfssl-py from pip. There's any way to enable SSL_RSA_WITH_RC4_128_SHA from the library (or during its installation)?

Thank you,
Regards

**Comment by dgarske** [comment]
Hi @xoda ,

For that cipher suite you will need `WOLFSSL_STATIC_RSA` defined. 

Try the following steps:

## Install Python3

1. Download latest Python 3.x and run installer: https://www.python.org/downloads
2. Check the box that says Add Python 3.x to PATH

## Install wolfCrypt

```sh
git clone https://github.com/wolfSSL/wolfssl.git
cd wolfssl
./configure --enable-keygen --enable-rsa --enable-ecc --enable-ed25519 --enable-des3 CFLAGS="-DWOLFSSL_PUBLIC_MP -DWOLFSSL_STATIC_RSA"
make
sudo make install
```

## Install wolfcrypt-py

```sh
git clone https://github.com/wolfSSL/wolfcrypt-py.git
cd wolfcrypt-py
sudo USE_LOCAL_WOLFSSL=/usr/local pip3 install .
```

Thanks,
David Garske, wolfSSL
