### ISSUE TITLE
DTLS server with PSK

### ISSUE THREAD

**Issue by mariusmotea** [wolfSSL/wolfssl-py#3]
Hi,

i know wolfssl library has support for TLS_PSK_WITH_AES_128_GCM_SHA256 cipher, but i cannot find how can i implement this in server.py example, if i manually specify it i get the following error:

```
root@ubuntu:/home/administrator/wolfssl# python3 server.py -l TLS_PSK_WITH_AES_128_GCM_SHA256
Server listening on port 2100
Traceback (most recent call last):
  File "dtls.py", line 126, in <module>
    main()
  File "dtls.py", line 96, in main
    context.set_ciphers(args.l)
  File "/usr/local/lib/python3.5/dist-packages/wolfssl/__init__.py", line 146, in set_ciphers
    raise SSLError("Unnable to set cipher list")

```
Any help will be appreciated.

Marius.

**Comment by kaleb-himes** [comment]
@mariusmotea,

Thank you for your questions! PSK is disabled by default in wolfSSL. If you update your build settings, please make sure the setting ```NO_PSK``` in not present and then add the setting ```WOLFSSL_STATIC_PSK``` to turn on the cipher suite ``` TLS_PSK_WITH_AES_128_GCM_SHA256```.

Let me know your results!

- Kaleb

**Comment by kaleb-himes** [comment]
Hi @mariusmotea,

We have not heard back from you for some time. Were you able to turn on the desired cipher suite support with the recommended setting?

- KH

**Comment by kaleb-himes** [comment]
@mariusmotea,

No problem, thanks for the feedback. Let us know if anything else comes up, for best response times please contact support@wolfssl.com any time, we are always happy to help in any way we can.
