### ISSUE TITLE
TLS v1.3

### ISSUE THREAD

**Issue by ggkitsas** [wolfSSL/wolfssl-py#4]
Hello,

Are there any plans to include bindings for the TLS v1.3 functionality? 

Best,
George

**Comment by kaleb-himes** [comment]
@ggkitsas,

It had not yet made it onto our roadmap but I would be happy to add it as a feature request on your behalf if you would like?

- KH

**Comment by ggkitsas** [comment]
@kaleb-himes,

Thank you.

Best regards,
George
