### ISSUE TITLE
Errors at free(), please update to latest wolfssl version.

### ISSUE THREAD

**Issue by rliebscher** [wolfSSL/wolfssl-py#50]
Hi,

when using wolfssl I got different errors about free(). (See below, I know I run some unusual case/code paths here, but that's intended by the code I have.)
I know that there were some fixes concerning free in wolfssl itself, so could you please update the included wolfssl to the latest version. Then I could check if my problems disappear.

```
double free or corruption (!prev)
Fatal Python error: Aborted

Current thread 0x0000007f59bab1c0 (most recent call first):
  File "/usr/local/lib/python3.9/dist-packages/wolfssl/__init__.py", line 473 in _release_native_object
  File "/usr/local/lib/python3.9/dist-packages/wolfssl/__init__.py", line 692 in shutdown
```

```
free(): invalid pointer
Fatal Python error: Aborted

Thread 0x0000007f5763e1c0 (most recent call first):
File "/usr/local/lib/python3.9/dist-packages/wolfssl/__init__.py", line 694 in shutdown
Fatal Python error: Segmentation fault
```

**Comment by embhorn** [comment]
@rliebscher Ask and you shall receive!
https://github.com/wolfSSL/wolfssl-py/pull/51
