### ISSUE TITLE
DTLS bindings

### ISSUE THREAD

**Issue by jarednm** [wolfSSL/wolfssl-py#7]
Are there any plans to create bindings for DTLS methods?

**Comment by cconlon** [comment]
Hi @jarednm,

We don't have immediate plans to add DTLS bindings, but I'll add this to our feature request list.  Thanks for the suggestion!

Best Regards,
Chris

**Comment by lealem47** [comment]
Hi @jarednm,

DTLS methods in wolfSSL-py have been implemented! I'll go ahead and close this issue now but feel free to reach out to support@wolfssl.com for any questions regarding wolfSSL-py.

Cheers,
Lealem
